apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: MIIDBzCCAe+gAwIBAgIURWkI4nR/O+PgdR8yOYZS998C3/QwDQYJKoZIhvcNAQEL
BQAwEjEQMA4GA1UEAwwHa3ViZS1jYTAgFw0yNDA2MDQyMzUwNDJaGA8yMDUxMTAy
MTIzNTA0MlowEjEQMA4GA1UEAwwHa3ViZS1jYTCCASIwDQYJKoZIhvcNAQEBBQAD
ggEPADCCAQoCggEBAL78Y5Gk8M/DEklvVgR0keA7lLzvpLA0FIADmgz/2wpyWLzp
I2jb7zNisxmsEhXkFfxVJGHA/UkSCCIHcaLX1p/tOtYdwrCtzSPq/YwPyPTpYclD
fig8AMuU3uJMtx/jzTxm/cSMHZsAPK68Ety8XyuxhlgIVLa3pM9P64EubN59o4T2
136XAtITQTkLvPO25Bc+y1DWPC9Y7fTBU7bzpoVrhx54IqSGaUtyubuBOBnHHor9
lPxxiVnWNkv7rmiMZqCXNGlFdHRmRyn+lvvz5zm1ZKC9DinlEL5FteVFfD1POHip
DyKVrGPfuhLGu5v1A3gb84zicUUN/1mFM09cS3ECAwEAAaNTMFEwHQYDVR0OBBYE
FHpYnYZh0f9R3vVUlS+C4f47RoF+MB8GA1UdIwQYMBaAFHpYnYZh0f9R3vVUlS+C
4f47RoF+MA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAJy/8Gvq
hsBE9PORd0OMi07bRDYsuo7PKIMYefTdFGQ3SzrmFRNbyGaqwt1Jqx5AUTqK7HQ3
zbJf91K6J0YW9JIZ7qVOLixBg2XkxF+6nOpsecYc8H+AeFOMyqbCeLJelcPBYAuK
oM1MxiphcnIK61oxN3bxn7Pxs1f70Qo2x383EOWd4jXB0P73XtZUDwHNYHZEdyOX
nIoBpP/gSbCNGPl9FesNR04H79Yf4IheNMe1nhnWuls4jWyUnp6JbrdS6olCr2k2
HReV+AVLVCDKcX9JOf6KrTWASsMyV6FqgByumcWK6AlCsjnZERBImANg09kyKw7t
WqE52rOXVD4357A=

    server: https://192.168.49.2:32103/
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: kube-user
  name: kubernetes-context
current-context: kubernetes-context
kind: Config
preferences: {}
users:
- name: kube-user
  user:
    client-certificate-data: MIIC9jCCAd6gAwIBAgIUWs5zkGZtNnfIBTB86IstaP0FRbEwDQYJKoZIhvcNAQEL
BQAwEjEQMA4GA1UEAwwHa3ViZS1jYTAeFw0yNDA2MDQyMzUxMTZaFw0yNTA2MDQy
MzUxMTZaMBQxEjAQBgNVBAMMCWt1YmUtdXNlcjCCASIwDQYJKoZIhvcNAQEBBQAD
ggEPADCCAQoCggEBANIsw0FwCGnUhEH6lfXctKmN0gOP/o0P2UUxsHJ+aGKqiBFm
Bv/0byTI7pf89LEPQQtnMWq7r6e4i3IsAh8T2FRqbVH+iwh/8nFIXTMctnGQyxTG
BD371c6KGRhRWrjmeo1R60xOv6SmtXXTz+lG0t4m/KLMCE9EWTkh3VVr7rNMJ+w/
8GHyn8ZgNh0lCCmk/KLJ1htEOCSEWh8psBFvHiDiqGxbWrVHohEGRP+5m2tzxs9c
VFhTJe8PLm1pIllWzIY7H2yc2LOL04u77d+mbGLpAiU+K9OZ/0gCeOmMva1Cdl4o
sGD9BbZbGE/4g+X3ngX4bNA3TzzX9C4R1g6cYyECAwEAAaNCMEAwHQYDVR0OBBYE
FNLJM3InQhrFoBQk35tJMxg5ZItsMB8GA1UdIwQYMBaAFHpYnYZh0f9R3vVUlS+C
4f47RoF+MA0GCSqGSIb3DQEBCwUAA4IBAQA+znHC+B03swNTqj1obsWpRXUKAqOR
PLaM1PlD0nUpMEBzo3+GntiU+NQ17uV4hGHMw+WMfEIz4AXq221QFqlX+zjKpqjw
hfRwo8VUYGgNMLJHOphpe90agkWPye0T0UFcZRs4GkFvvaB4l9ylAl9N4QgRC6Mk
0R/rB2nuOZXfxNh1pgtkClBBS99svPJJOL9FUTpI2xRoNKSsZ38HyKlZiaowSSEG
6O4ILcNuaNaWiYGKsAyp7cE3+Xuk5NkpcYStKfq6ZG1xPEuYaewd2o/8x9CB7yY3
4E/fIO17L6H22+H3MrrKMkwo+7stIcGlyIHmVXAinnM2bYEfMK0u3iLt
    client-key-data: MIICWTCCAUECAQAwFDESMBAGA1UEAwwJa3ViZS11c2VyMIIBIjANBgkqhkiG9w0B
AQEFAAOCAQ8AMIIBCgKCAQEA0izDQXAIadSEQfqV9dy0qY3SA4/+jQ/ZRTGwcn5o
YqqIEWYG//RvJMjul/z0sQ9BC2cxaruvp7iLciwCHxPYVGptUf6LCH/ycUhdMxy2
cZDLFMYEPfvVzooZGFFauOZ6jVHrTE6/pKa1ddPP6UbS3ib8oswIT0RZOSHdVWvu
s0wn7D/wYfKfxmA2HSUIKaT8osnWG0Q4JIRaHymwEW8eIOKobFtatUeiEQZE/7mb
a3PGz1xUWFMl7w8ubWkiWVbMhjsfbJzYs4vTi7vt36ZsYukCJT4r05n/SAJ46Yy9
rUJ2XiiwYP0FtlsYT/iD5feeBfhs0DdPPNf0LhHWDpxjIQIDAQABoAAwDQYJKoZI
hvcNAQELBQADggEBAIH/XQ21xfUByXooPdRlxvjVDd1S5Z5/iH1p9GA97tn0r88f
DLDrKlbuzFiCOH0o+sm9xZA0sHUH1B+170FmN2gIYrXM8IwE0iK7Web4QQHKUZB/
yZdb+YiumypH+iVJBLLHWnGbMHO7DwLC978sMI1eny1HGIoaQgYPsNsN5cZk0RR6
4mjQfrqJYLbSBY94wYs/hIMzrUWrnd8jrUt952GChKRYQOjoHaBhXCUdngQ0YWJb
pSLdylOLddm0VYca4372+xy26Vjv5BvVXkhPcm+k7/LQRQSbHJYs5SNng+Unp2Sb
HVjZINCpuLCBRDWVfEt82LqUi0LScf5aLO2ANwE=